In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/ogrisel/parallel_ml_tutorial/master/notebooks/titanic_train.csv',sep=",")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [4]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
df[['Name','Sex','Ticket','Cabin','Embarked']].

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [7]:
a=df.dtypes[df.dtypes==object].index
a
df[a].describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [11]:
b=df.dtypes[df.dtypes=='int64'].index
df[b].describe()

PassengerId    Survived      Pclass       SibSp       Parch
count   891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642    0.523008    0.381594
std     257.353842    0.486592    0.836071    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000    0.000000    0.000000
50%     446.000000    0.000000    3.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000    8.000000    6.000000

In [14]:
sorted(df['Name'])[5:10:2]

['Adahl, Mr. Mauritz Nils Martin',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Albimona, Mr. Nassef Cassem']

In [15]:
df[["Name"]][::2]

Name
0                              Braund, Mr. Owen Harris
2                               Heikkinen, Miss. Laina
4                             Allen, Mr. William Henry
6                              McCarthy, Mr. Timothy J
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
..                                                 ...
882                       Dahlberg, Miss. Gerda Ulrika
884                             Sutehall, Mr. Henry Jr
886                              Montvila, Rev. Juozas
888           Johnston, Miss. Catherine Helen "Carrie"
890                                Dooley, Mr. Patrick

[446 rows x 1 columns]

In [25]:
b=[sorted(df['Name'])[::]]

In [27]:
print(b)

[['Abbing, Mr. Anthony', 'Abbott, Mr. Rossmore Edward', 'Abbott, Mrs. Stanton (Rosa Hunt)', 'Abelson, Mr. Samuel', 'Abelson, Mrs. Samuel (Hannah Wizosky)', 'Adahl, Mr. Mauritz Nils Martin', 'Adams, Mr. John', 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'Aks, Mrs. Sam (Leah Rosen)', 'Albimona, Mr. Nassef Cassem', 'Alexander, Mr. William', 'Alhomaki, Mr. Ilmari Rudolf', 'Ali, Mr. Ahmed', 'Ali, Mr. William', 'Allen, Miss. Elisabeth Walton', 'Allen, Mr. William Henry', 'Allison, Master. Hudson Trevor', 'Allison, Miss. Helen Loraine', 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)', 'Allum, Mr. Owen George', 'Andersen-Jensen, Miss. Carla Christine Nielsine', 'Anderson, Mr. Harry', 'Andersson, Master. Sigvard Harald Elias', 'Andersson, Miss. Ebba Iris Alfrida', 'Andersson, Miss. Ellis Anna Maria', 'Andersson, Miss. Erna Alexandra', 'Andersson, Miss. Ingeborg Constanzia', 'Andersson, Miss. Sigrid Elisabeth', 'Andersson, Mr. Anders Johan', 'Andersson, Mr. August Edvard ("Wennerstrom")'

In [28]:
import numpy as np

In [29]:
char_cabin=df['Cabin'].astype(str)
new_cabin=[i[0] for i in char_cabin]
df['cabin_1']=new_cabin

In [31]:
char_cabin

0       nan
1       C85
2       nan
3      C123
4       nan
       ... 
886     nan
887     B42
888     nan
889    C148
890     nan
Name: Cabin, Length: 891, dtype: object

In [33]:
df['Age'].isnull().sum()

177

In [34]:
df.shape

(891, 13)

In [35]:
np.where(df['Age'].isnull()==True)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [36]:
max(df['Fare'])

512.3292

In [37]:
np.where(df['Fare']==max(df['Fare']))

(array([258, 679, 737], dtype=int64),)

In [40]:
df.iloc[[258,679,737]]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  \
258  female  35.0      0      0  PC 17755  512.3292          NaN        C   
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C   
737    male  35.0      0      0  PC 17755  512.3292         B101        C   

    cabin_1  
258       n  
679       B  
737       B

In [42]:
np.where(df["Age"]==min(df['Age']))

(array([803], dtype=int64),)

In [44]:
df.iloc[(np.where(df['Age']==min(df['Age'])))]

PassengerId  Survived  Pclass                             Name   Sex  \
803          804         1       3  Thomas, Master. Assad Alexander  male   

      Age  SibSp  Parch Ticket    Fare Cabin Embarked cabin_1  
803  0.42      0      1   2625  8.5167   NaN        C       n

In [45]:
df.iloc[(np.where(df['Age']==min(df['Age'])))][['Name','Age','Cabin']]

Name   Age Cabin
803  Thomas, Master. Assad Alexander  0.42   NaN

In [46]:
df['Family']=df['SibSp']+df['Parch']

In [47]:
df['Family']

0      1
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    3
889    0
890    0
Name: Family, Length: 891, dtype: int64

In [48]:
most_fam=np.where(df['Family']==max(df['Family']))


In [49]:
df.iloc[most_fam]

PassengerId  Survived  Pclass                               Name     Sex  \
159          160         0       3         Sage, Master. Thomas Henry    male   
180          181         0       3       Sage, Miss. Constance Gladys  female   
201          202         0       3                Sage, Mr. Frederick    male   
324          325         0       3           Sage, Mr. George John Jr    male   
792          793         0       3            Sage, Miss. Stella Anna  female   
846          847         0       3           Sage, Mr. Douglas Bullen    male   
863          864         0       3  Sage, Miss. Dorothy Edith "Dolly"  female   

     Age  SibSp  Parch    Ticket   Fare Cabin Embarked cabin_1  Family  
159  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
180  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
201  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
324  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
792  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
846  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
863  NaN      8      2  CA. 2343  69.55   NaN        S       n      10

In [57]:
from numpy.random import randn as rn
matrix_data=rn(5,4)
col_index=['A','B','C','D']

df=pd.DataFrame(matrix_data,columns=col_index)

In [58]:
df

A         B         C         D
0  2.548913  0.249747 -0.391242 -0.248220
1 -0.074258 -1.821122 -1.070147  1.463655
2  1.192349  2.553071 -0.422432  0.255911
3 -0.758924 -1.134625  0.717787  1.281523
4  0.251076 -1.601992  0.795048 -0.528331

In [61]:
df.iloc[0]

A    2.548913
B    0.249747
C   -0.391242
D   -0.248220
Name: 0, dtype: float64

In [62]:
df.iloc[[4,1,2],[1]]

B
4 -1.601992
1 -1.821122
2  2.553071

In [69]:
df.loc[[1,2],['B','C']]

B         C
1 -1.821122 -1.070147
2  2.553071 -0.422432

In [71]:
df.iloc[[0,4],[0,3]]

A         D
0  2.548913 -0.248220
4  0.251076 -0.528331

In [85]:
df.iloc[1:5,0:3]

A         B         C
1 -0.074258 -1.821122 -1.070147
2  1.192349  2.553071 -0.422432
3 -0.758924 -1.134625  0.717787
4  0.251076 -1.601992  0.795048

In [86]:
df.drop('A',axis=1)

B         C         D
0  0.249747 -0.391242 -0.248220
1 -1.821122 -1.070147  1.463655
2  2.553071 -0.422432  0.255911
3 -1.134625  0.717787  1.281523
4 -1.601992  0.795048 -0.528331

In [87]:
df

A         B         C         D
0  2.548913  0.249747 -0.391242 -0.248220
1 -0.074258 -1.821122 -1.070147  1.463655
2  1.192349  2.553071 -0.422432  0.255911
3 -0.758924 -1.134625  0.717787  1.281523
4  0.251076 -1.601992  0.795048 -0.528331

In [88]:
df.drop('A',inplace=True,axis=1)

In [89]:
df

B         C         D
0  0.249747 -0.391242 -0.248220
1 -1.821122 -1.070147  1.463655
2  2.553071 -0.422432  0.255911
3 -1.134625  0.717787  1.281523
4 -1.601992  0.795048 -0.528331

In [91]:
df.drop(0)

B         C         D
1 -1.821122 -1.070147  1.463655
2  2.553071 -0.422432  0.255911
3 -1.134625  0.717787  1.281523
4 -1.601992  0.795048 -0.528331

In [92]:
df

B         C         D
0  0.249747 -0.391242 -0.248220
1 -1.821122 -1.070147  1.463655
2  2.553071 -0.422432  0.255911
3 -1.134625  0.717787  1.281523
4 -1.601992  0.795048 -0.528331

In [95]:
df.ix[[0]]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [96]:
!pip install ix

In [98]:
df.ix[[0]]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [102]:
print('\nConditional problem\n','-'*30,sep=' ')
print(df>0)


Conditional problem
 ------------------------------
       B      C      D
0   True  False  False
1  False  False   True
2   True  False   True
3  False   True   True
4  False   True  False


In [108]:
#Matrix to DataFrame
import numpy as np
matrix_data=np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')

matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [109]:
row_labels=['A','B','C','D','E']
column=['Age','Height','Weight']

In [110]:
dff=pd.DataFrame(matrix_data,row_labels,column)

In [111]:
dff

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [116]:
dff[dff['Height']<65]

Age  Height  Weight
C   30      62     125
E   25      62     152

In [126]:
dff[(dff['Age']>25) & (dff['Height']<65)]

Age  Height  Weight
C   30      62     125

In [15]:
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [16]:
hier_index=pd.MultiIndex.from_tuples(hier_index)
print(hier_index)

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )


In [17]:
import pandas as pd
from numpy.random import randn as rn

In [18]:
df3=pd.DataFrame(data=np.round(rn(6,3)),index=hier_index,columns=['A','B','C'])
print(df3)

        A    B    C
G1 1  1.0 -1.0 -1.0
   2 -0.0  1.0  0.0
   3  1.0  0.0 -1.0
G2 1  1.0  1.0  2.0
   2 -1.0 -0.0  2.0
   3 -2.0 -0.0 -1.0


In [38]:
df3.loc['G1'].loc[3,['B','C']]

B    0.0
C   -1.0
Name: 3, dtype: float64

In [40]:
l1=['A','A','A','B','B','B','C','C','C']
l2=[1,2,3,1,2,3,1,2,3]
l3=[1,2,3,4,5,6,7,8,9]

hier_index1=list(zip(l1,l2,l3))

In [42]:
hier_index1

[('A', 1, 1),
 ('A', 2, 2),
 ('A', 3, 3),
 ('B', 1, 4),
 ('B', 2, 5),
 ('B', 3, 6),
 ('C', 1, 7),
 ('C', 2, 8),
 ('C', 3, 9)]

In [43]:
g=pd.MultiIndex.from_tuples(hier_index1)
df5=pd.DataFrame(data=np.round(rn(9,4)),index=g)

In [44]:
df5

0    1    2    3
A 1 1 -3.0 -0.0  0.0 -0.0
  2 2  1.0 -1.0 -1.0  0.0
  3 3 -1.0  1.0 -1.0  1.0
B 1 4  0.0  0.0  0.0 -0.0
  2 5  1.0  1.0  1.0  0.0
  3 6 -2.0 -1.0 -1.0 -0.0
C 1 7  1.0 -1.0  0.0  2.0
  2 8  0.0 -1.0  1.0  0.0
  3 9  1.0  0.0  2.0  0.0